### ISSUE TITLE
Updating the data

### ISSUE THREAD

**Issue by sumanstats** [mesaugat/geoJSON-Nepal#1]
Hi,

Nepal currently have 77 districts as per new constitution.
It would be great if its reflected in your data.

Nice effort keeping data of our country and make it accessible.

Thank you.

**Comment by mesaugat** [comment]
@sumandoc Hey thanks. I'll see what I can do.

If you can send in a PR it would be great too. 😉

**Comment by sumanstats** [comment]
@mesaugat I came across this `.geojson` file showing all 77 districts.

https://github.com/Acesmndr/nepal-geojson/blob/master/generated-geojson/nepal-acesmndr.geojson

You can update with this file hopefully !

**Comment by mesaugat** [comment]
@sumandoc Thanks!

I think I won't be able to use this to update my GeoJSON file. The one I have is higher quality and has more geometries than the one you mentioned. I'll see what I can do.

**Comment by sumanstats** [comment]
@mesaugat No worries !

I have used your `geojson` data here:

https://stackoverflow.com/questions/50859765/chloropleth-map-with-geojson-and-ggplot2

Hopefully you can have another repo for 77 districts!

**Comment by mesaugat** [comment]
@sumandoc Awesome!

**Comment by JayanthanSivaloganthan** [comment]
Hi guys, i was trying to upload json files to mapbox, it does not work, can you please help

**Comment by JayanthanSivaloganthan** [comment]
http://localboundries.oknp.org/

**Comment by mesaugat** [comment]
@JayanthanSivaloganthan Upload JSON files to mapbox? What do you mean?

**Comment by mesaugat** [comment]
I see that your website is working fine, the GeoJSON seems to be working properly.

**Comment by JayanthanSivaloganthan** [comment]
Hi Guys

Nepal Map does not have the latest districts and municipals. We would require the latest map to deliver our client


E.g 
Rukum East , Rukum West , Nawalparasi East and Nawalparasi West

Thank You 
Jayanthan

**Comment by mesaugat** [comment]
@JayanthanSivaloganthan Does this work? https://github.com/mesaugat/geoJSON-Nepal/blob/master/nepal-municipalities.geojson

**Comment by JayanthanSivaloganthan** [comment]
> @JayanthanSivaloganthan Does this work? https://github.com/mesaugat/geoJSON-Nepal/blob/master/nepal-municipalities.geojson

@mesaugat.Yes. it works, we have converted the file into Topojson format and uploaded our business intelligence tool

**Comment by JayanthanSivaloganthan** [comment]
> > @JayanthanSivaloganthan Does this work? https://github.com/mesaugat/geoJSON-Nepal/blob/master/nepal-municipalities.geojson
> 
> @mesaugat.Yes. it works, we have converted the file into Topojson format and uploaded our business intelligence tool

@mesaugat, I think there is an issue with topojson conversion. Do you have https://github.com/mesaugat/geoJSON-Nepal/blob/master/nepal-municipalities.geojson in topojson?

**Comment by mesaugat** [comment]
@JayanthanSivaloganthan I don't have the `topojson` format either. You can look for other converters.

**Comment by JayanthanSivaloganthan** [comment]
> @JayanthanSivaloganthan I don't have the `topojson` format either. You can look for other converters.

do you have municipalities and districts  in Excel or CSV format. Appreciate if you could share

**Comment by JayanthanSivaloganthan** [comment]
Hi Guys, 

Municipality ID 577 shows blanks in https://github.com/mesaugat/geoJSON-Nepal/blob/master/nepal-municipalities.geojson

Please advise
