### ISSUE TITLE
Map of whole Nepal

### ISSUE THREAD

**Issue by sumanstats** [mesaugat/geoJSON-Nepal#6]
Hi there,

Do you have geojson file that includes all of our territories as per our new map? Could you make one?

**Comment by mesaugat** [comment]
Hello @sumanstats I don't have the geojson file that includes all the latest territories. This other repo has all of them. 👉 https://github.com/Acesmndr/nepal-geojson

**Comment by sumanstats** [comment]
Got it. Thank you.
