### ISSUE TITLE
Nepal New change in the Map

### ISSUE THREAD

**Issue by JayanthanSivaloganthan** [mesaugat/geoJSON-Nepal#7]
Hi Guys,

Nepal has included additional locations into their maps. Will possible to include them into json files. Thanks

![image](https://user-images.githubusercontent.com/43981743/87294657-ac16f600-c521-11ea-9c01-2052b7b4c030.png)

https://myrepublica.nagariknetwork.com/uploads/media/Nepalwithlipiyadhura_20200509204543.jpg
https://myrepublica.nagariknetwork.com/news/ndia-began-construction-of-controversial-road-12-years-ago-nepal-is-unaware/

Regards,
Jayanthan

**Comment by mesaugat** [comment]
Hello @JayanthanSivaloganthan, this repository has the latest updates. 👉  https://github.com/Acesmndr/nepal-geojson
